version: '2.1'

services:
  nginx:
    volumes:
      - static-volume:/srv/static
  backup:
    build: './backup'
    links:
      - mysql:mysql-docker
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - DROPBOX_ACCESS_TOKEN=$DROPBOX_ACCESS_TOKEN
    volumes:
      - mediawiki-volume:/srv/mediawiki
  jobs:
    build: './jobs'
    environment:
      - BATMAN_BOT_PASSWORD=$BATMAN_BOT_PASSWORD
      - GOOGLE_ANALYTICS_SERVICE_KEY=$GOOGLE_ANALYTICS_SERVICE_KEY

volumes:
  mediawiki-volume:
  static-volume:
