version: '2'

services:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=metakgp_wiki_db
      - MYSQL_USER=metakgp_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
  nginx:
    build: './nginx'
    links:
      - php:php-docker
    volumes:
      - mediawiki-volume:/srv/mediawiki
    ports:
      - "$SERVER_PORT:80"
  php:
    build: './php'
    links:
      - mysql:mysql-docker
    volumes:
      - mediawiki-volume:/srv/mediawiki
    environment:
      - MAILGUN_PASSWORD=$MAILGUN_PASSWORD
      - RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
      - WG_SECRET_KEY=$WG_SECRET_KEY
      - SITE_UPGRADE_KEY=$SITE_UPGRADE_KEY
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - SERVER_NAME=$SERVER_NAME
  mediawiki:
    build: './mediawiki'
    volumes:
      - mediawiki-volume:/srv/mediawiki
  backup:
    build: './backup'
    links:
      - mysql:mysql-docker
    volumes:
      - mediawiki-volume:/srv/mediawiki
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - DROPBOX_ACCESS_TOKEN=$DROPBOX_ACCESS_TOKEN

volumes:
  mediawiki-volume:
  db-volume:
