version: '2.1'

services:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=metakgp_wiki_db
      - MYSQL_USER=metakgp_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  nginx:
    build: './nginx'
    links:
      - php:php-docker
  php:
    build: './php'
    links:
      - mysql:mysql-docker
    environment:
      - MAILGUN_PASSWORD=$MAILGUN_PASSWORD
      - RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
      - WG_SECRET_KEY=$WG_SECRET_KEY
      - SITE_UPGRADE_KEY=$SITE_UPGRADE_KEY
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - SERVER_NAME=$SERVER_NAME
  mediawiki:
    build: './mediawiki'
